### ISSUE TITLE
Unfriendly chars in sample names crash

### ISSUE THREAD

**Issue by sinfloodmusic** [dbrookman/trackrip#1]
Great work on this, it's going to save me a ton of time on a project.  I noticed it crashes when the sample names aren't filesystem friendly.  This is especially prevalent in cracktro mods, where the samples are mostly one-way discussions to other people in the demo scene at the time.

Here is an example mod that crashes the program: [https://api.modarchive.org/downloads.php?moduleid=65240#s.o.c-introsong.mod](https://api.modarchive.org/downloads.php?moduleid=65240#s.o.c-introsong.mod)

I don't want to submit an unsolicited PR, happy to send it though.  It was a few lines to just do a regex on the filename and ensure that any unfriendly chars are changed to '_'

**__main__.py**
```
sample_file_name = re.sub(r'[^\w\d-]','_',sample_file_name)
sample_file_name += ".wav"
```

**Comment by dbrookman** [comment]
Very happy to hear this will help, and thanks for submitting this. What OS / filesystem are you using?

I did a look around, and how is there nothing in the python standard library for this? I think your method is probably the best for now. I'd also add `\s` to the expression, like `r'[^\w\s\d-]'` if spaces aren't also restricted.

Please feel free to submit this as a PR, I don't mind at all, and would prefer people get properly credited!
I'll add a contributing file at some point soon.

**Comment by sinfloodmusic** [comment]
Whoops, OS would be kind of important.  As you likely suspected, Windows 10.  

Great!  Good call on the spaces, I think it was the '?' in that mod that was giving windows fits.

Will submit a PR today.

**Comment by sinfloodmusic** [comment]
It appears I don't have access to submit a PR on a new branch I've created.

**Comment by dbrookman** [comment]
File systems are extremely evil. 😭

> It appears I don't have access to submit a PR on a new branch I've created.

GitHub can get a little annoying when you're first submitting pull requests, but here's some quick steps that should work in this case. If I'm assuming too much or too little, or if it's actually on my end, please let me know!

1. You'll want to fork this repo on GitHub (there's a button for it in the top right, under the header).
That should create `https://github.com/sinfloodmusic/trackrip`, your own version of the repo that you can make changes to.

2. If you've already cloned this repo (the one with this message) to your computer, all you need to do is change the remote URL to your fork's.
Running `git remote set-url origin https://github.com/sinfloodmusic/trackrip.git` will do that.

3. After switching the URL, you'll want to run `git push -u origin <name-of-your-branch>` to sync the branch and it's commits to your fork on GitHub.

4. Back on GitHub, you'll want to switch to your branch either by going to `https://github.com/sinfloodmusic/trackrip/tree/<name-of-your-branch>`, or by using the branch select menu on the "Code" page.

5. At your new branch, you should see a gray bar with some text that says something like "_This branch is 1 commit ahead of trackrip:main_". Hit where it says "Contribute" to the right of that text, and then click the "Open pull request" button.

**Comment by sinfloodmusic** [comment]
Thank you!  You were spot on, I didn't realize I needed to fork the repo to make a PR.  Thanks and hope this helps!
